### ISSUE TITLE
Full rooms are displayed in `list_chats`

### ISSUE THREAD

**Issue by nekonekonik** [CS3216-Bubble/bubble#19]
Not sure whether its a bug or feature again but full rooms are displayed in `list_chats`

![screenshot 2016-10-23 15 22 11](https://cloud.githubusercontent.com/assets/7563985/19624686/e90f5df8-9934-11e6-8c2b-91850303b325.png)

Steps to recreate:
1. Use front-end to create room for 2 people (or some other way)
2. Use second tab to join the created room (Frontend or backend demo user)
3. Use third tab to view list of rooms

**Comment by ngzhian** [comment]
as discussed :)
